language: ruby
rvm:
  - 2.4.1
bundler_args: --without test --jobs 3 --retry 3
before_install:
  - gem update bundler
  - bundle install
  - bundle binstubs rake
  - bin/rake deps
script:
  - bin/rake test
services:
  - mysql
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
